### ISSUE TITLE
block indexing seems to have bugs

### ISSUE THREAD

**Issue by zqkhan** [neu-spiral/HTFATorch#44]
**Issue:**
the indexing for "blocks" seems to not match when referring to:

self._dataset.blocks[block] (e.g. in lines 340 to 343 in dtfa.py)

vs

self._dataset[block] (e.g. in line 422 in dtfa.py)

**How to reproduce**
an example of this can be seen in notebooks/affvids_norest_mini_bug_demo.ipynb

where block=45 results in dtfa._dataset[45] referring to subject 25's data.
<img width="532" alt="Capture" src="https://user-images.githubusercontent.com/10852368/140002546-819fb3a0-f2cd-4ebd-9396-d923f2e34e82.PNG">

while dtfa._dataset.blocks[45] points to subject 26. (file titled capture2.png here)
<img width="546" alt="Capture2" src="https://user-images.githubusercontent.com/10852368/140002556-d2d9dde4-00fa-42d7-b2c0-0ae22e657f6b.PNG">

the dataloading notebook for this is in notebooks/AffVids2018_MC_restz_norest_mini_tardb_for_bug_demo.ipynb which is just to create a tiny 3 participant version of the affvids dataset. the only difference between this dataloading notebook and the full one in notebooks/AffVids2018_MC_restz_norest_tardb.ipynb is that it excludes a bunch of subjects using 
exclude_subjects = [8, 23, 6, 17, 19, 29, 14, 12, 11, 16, 15, 13, 28, 29, 4, 5, 10, 9, 18]

**Implication**
In none of my runs on this or the new data or with new model do the embeddings seem strange. if this was impacting our training that'd have happened. 
This bug however probably does effect the reconstruction_diff calculations and also makes it hard to compare output of plot_original() with plot_reconstruction() since those two are probably referring to different blocks. 
line 422 activations = self._dataset[block]['activations'] in dtfa.py will pull participant 25's activations
lines 340 to 343 in dtfa.py will lead to reconstructions from participant 26.

**Comment by esennesh** [comment]
Should be fixed in this branch.  Did we never merge it? https://github.com/neu-pml/HTFATorch/tree/bugfix/block_indexing
